title: IB-BIM Visibility Manager Docs
description: Official User and Technical Documentation
theme: minima
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - UserGuide.md
  - UserGuide_he.md
  - FAQ.md
  - LICENSING.md
