title: IB-BIM Visibility Manager â€” User Guide
description: Official documentation and user guide for IB-BIM Visibility Manager add-in for Autodesk Revit.
theme: just-the-docs
logo: /Images/VG Screen.png
color_scheme: light

nav_order: 1
search_enabled: true
